# Generated by Django 4.2.6 on 2023-10-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_room_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Room name"),
        ),
    ]
