# Generated by Django 4.2.6 on 2024-01-19 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0008_messagerecipient_alter_message_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="chat.message",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="roomparticipant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="roomparticipant",
            name="room",
        ),
        migrations.RemoveField(
            model_name="roomparticipant",
            name="user",
        ),
        migrations.DeleteModel(
            name="MessageRecipient",
        ),
        migrations.DeleteModel(
            name="RoomParticipant",
        ),
    ]
