# Generated by Django 4.2.6 on 2024-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="screen_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="screen name"
            ),
        ),
    ]
